name = 'typo-tim'
license = 'MIT'
licenselink = 'https://github.com/tomfran/typo/blob/main/LICENSE'
description = 'Personal fork of Typo theme with resume, gallery, and enhanced features'

homepage = 'https://ttyt.me'

demosite = 'https://ttyt.me'

tags = [
    "responsive",
    "simple",
    "clean",
    "light",
    "dark",
    "blog",
    "minimal",
    "personal",
    "portfolio",
    "resume",
    "cv",
    "gallery",
]

features = [
    "responsive",
    "blog",
    "resume-cv",
    "photo-gallery",
    "table-of-contents",
    "highlight.js",
    "favicon",
    "social-icons",
    "minified-assets",
    "dark-light-images",
    "color-palettes",
    "font-awesome-icons",
]

[author]
name = 'Timothy Tang (based on Typo by Francesco Tomaselli)'
homepage = 'https://ttyt.me'

[original]
name = 'Francesco Tomaselli'
homepage = 'https://tomfran.github.io/'
theme = 'Typo'
repo = 'https://github.com/tomfran/typo'
